// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoChatingApp.WebRTC.Data;

#nullable disable

namespace VideoChatingApp.WebRTC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260908133948_AddSessionReadyAndReminder")]
    partial class AddSessionReadyAndReminder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.13");

            modelBuilder.Entity("VideoChatingApp.WebRTC.Core.Models.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttachmentType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("AttachmentUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ConversationId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SenderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("IsRead");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.HasIndex("SentAt");

                    b.HasIndex("SenderId", "ReceiverId", "SentAt");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("VideoChatingApp.WebRTC.Core.Models.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastMessageAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UnreadCountUser1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnreadCountUser2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("User1Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("User2Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LastMessageAt");

                    b.HasIndex("User2Id");

                    b.HasIndex("User1Id", "User2Id")
                        .IsUnique();

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("VideoChatingApp.WebRTC.Core.Models.Friendship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("User1Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("User2Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("User1Id");

                    b.HasIndex("User2Id");

                    b.HasIndex("User1Id", "User2Id")
                        .IsUnique();

                    b.ToTable("Friendships");
                });

            modelBuilder.Entity("VideoChatingApp.WebRTC.Core.Models.FriendshipRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SenderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.HasIndex("Status");

                    b.HasIndex("SenderId", "ReceiverId", "Status");

                    b.ToTable("FriendshipRequests");
                });

            modelBuilder.Entity("VideoChatingApp.WebRTC.Core.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("VideoChatingApp.WebRTC.Core.Models.PostComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PostId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PostId");

                    b.ToTable("PostComments");
                });

            modelBuilder.Entity("VideoChatingApp.WebRTC.Core.Models.PostReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PostId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.HasIndex("PostId", "UserId")
                        .IsUnique();

                    b.ToTable("PostReactions");
                });

            modelBuilder.Entity("VideoChatingApp.WebRTC.Core.Models.PushSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Auth")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("P256dh")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PushSubscriptions");
                });

            modelBuilder.Entity("VideoChatingApp.WebRTC.Core.Models.SubjectTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SubjectTags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Algebra, Calculus, Statistics, Geometry",
                            Icon = "📐",
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Mechanics, Thermodynamics, Electromagnetism",
                            Icon = "⚛️",
                            Name = "Physics"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Organic, Inorganic, Physical Chemistry",
                            Icon = "🧪",
                            Name = "Chemistry"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Cell Biology, Genetics, Ecology",
                            Icon = "🧬",
                            Name = "Biology"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Programming, Algorithms, Data Structures",
                            Icon = "💻",
                            Name = "Computer Science"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Grammar, Writing, Literature",
                            Icon = "📝",
                            Name = "English"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Conversational, Grammar, Writing",
                            Icon = "🗣️",
                            Name = "Spanish"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Conversational, Grammar, Writing",
                            Icon = "🥐",
                            Name = "French"
                        },
                        new
                        {
                            Id = 9,
                            Description = "World History, US History, European History",
                            Icon = "📜",
                            Name = "History"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Micro, Macroeconomics, Finance",
                            Icon = "📊",
                            Name = "Economics"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Piano, Guitar, Theory, Vocal",
                            Icon = "🎵",
                            Name = "Music"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Drawing, Painting, Digital Art",
                            Icon = "🎨",
                            Name = "Art"
                        });
                });

            modelBuilder.Entity("VideoChatingApp.WebRTC.Core.Models.TeacherAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("TeacherProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeacherProfileId", "DayOfWeek");

                    b.ToTable("TeacherAvailabilities");
                });

            modelBuilder.Entity("VideoChatingApp.WebRTC.Core.Models.TeacherProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HourlyRate")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAcceptingStudents")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsAcceptingStudents");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("TeacherProfiles");
                });

            modelBuilder.Entity("VideoChatingApp.WebRTC.Core.Models.TeacherSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubjectTagId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeacherProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SubjectTagId");

                    b.HasIndex("TeacherProfileId", "SubjectTagId")
                        .IsUnique();

                    b.ToTable("TeacherSubjects");
                });

            modelBuilder.Entity("VideoChatingApp.WebRTC.Core.Models.TutoringReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Rating");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("TutoringReviews");
                });

            modelBuilder.Entity("VideoChatingApp.WebRTC.Core.Models.TutoringSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ReminderSent")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StudentNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SubjectTagId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TeacherNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScheduledAt");

                    b.HasIndex("Status");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectTagId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TutoringSessions");
                });

            modelBuilder.Entity("VideoChatingApp.WebRTC.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsOnline");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VideoChatingApp.WebRTC.Core.Models.ChatMessage", b =>
                {
                    b.HasOne("VideoChatingApp.WebRTC.Core.Models.Conversation", null)
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId");

                    b.HasOne("VideoChatingApp.WebRTC.Core.Models.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VideoChatingApp.WebRTC.Core.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("VideoChatingApp.WebRTC.Core.Models.Conversation", b =>
                {
                    b.HasOne("VideoChatingApp.WebRTC.Core.Models.User", "User1")
                        .WithMany()
                        .HasForeignKey("User1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VideoChatingApp.WebRTC.Core.Models.User", "User2")
                        .WithMany()
                        .HasForeignKey("User2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("VideoChatingApp.WebRTC.Core.Models.Friendship", b =>
                {
                    b.HasOne("VideoChatingApp.WebRTC.Core.Models.User", "User1")
                        .WithMany("FriendshipsAsUser1")
                        .HasForeignKey("User1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VideoChatingApp.WebRTC.Core.Models.User", "User2")
                        .WithMany("FriendshipsAsUser2")
                        .HasForeignKey("User2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("VideoChatingApp.WebRTC.Core.Models.FriendshipRequest", b =>
                {
                    b.HasOne("VideoChatingApp.WebRTC.Core.Models.User", "Receiver")
                        .WithMany("ReceivedRequests")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VideoChatingApp.WebRTC.Core.Models.User", "Sender")
                        .WithMany("SentRequests")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("VideoChatingApp.WebRTC.Core.Models.Post", b =>
                {
                    b.HasOne("VideoChatingApp.WebRTC.Core.Models.User", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("VideoChatingApp.WebRTC.Core.Models.PostComment", b =>
                {
                    b.HasOne("VideoChatingApp.WebRTC.Core.Models.User", "Author")
                        .WithMany("PostComments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VideoChatingApp.WebRTC.Core.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("VideoChatingApp.WebRTC.Core.Models.PostReaction", b =>
                {
                    b.HasOne("VideoChatingApp.WebRTC.Core.Models.Post", "Post")
                        .WithMany("Reactions")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoChatingApp.WebRTC.Core.Models.User", "User")
                        .WithMany("PostReactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VideoChatingApp.WebRTC.Core.Models.TeacherAvailability", b =>
                {
                    b.HasOne("VideoChatingApp.WebRTC.Core.Models.TeacherProfile", "TeacherProfile")
                        .WithMany("AvailabilitySlots")
                        .HasForeignKey("TeacherProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeacherProfile");
                });

            modelBuilder.Entity("VideoChatingApp.WebRTC.Core.Models.TeacherProfile", b =>
                {
                    b.HasOne("VideoChatingApp.WebRTC.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VideoChatingApp.WebRTC.Core.Models.TeacherSubject", b =>
                {
                    b.HasOne("VideoChatingApp.WebRTC.Core.Models.SubjectTag", "SubjectTag")
                        .WithMany()
                        .HasForeignKey("SubjectTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoChatingApp.WebRTC.Core.Models.TeacherProfile", "TeacherProfile")
                        .WithMany("Subjects")
                        .HasForeignKey("TeacherProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubjectTag");

                    b.Navigation("TeacherProfile");
                });

            modelBuilder.Entity("VideoChatingApp.WebRTC.Core.Models.TutoringReview", b =>
                {
                    b.HasOne("VideoChatingApp.WebRTC.Core.Models.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VideoChatingApp.WebRTC.Core.Models.TutoringSession", "Session")
                        .WithMany("Reviews")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reviewer");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("VideoChatingApp.WebRTC.Core.Models.TutoringSession", b =>
                {
                    b.HasOne("VideoChatingApp.WebRTC.Core.Models.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VideoChatingApp.WebRTC.Core.Models.SubjectTag", "SubjectTag")
                        .WithMany()
                        .HasForeignKey("SubjectTagId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VideoChatingApp.WebRTC.Core.Models.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("SubjectTag");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("VideoChatingApp.WebRTC.Core.Models.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("VideoChatingApp.WebRTC.Core.Models.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("VideoChatingApp.WebRTC.Core.Models.TeacherProfile", b =>
                {
                    b.Navigation("AvailabilitySlots");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("VideoChatingApp.WebRTC.Core.Models.TutoringSession", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("VideoChatingApp.WebRTC.Core.Models.User", b =>
                {
                    b.Navigation("FriendshipsAsUser1");

                    b.Navigation("FriendshipsAsUser2");

                    b.Navigation("PostComments");

                    b.Navigation("PostReactions");

                    b.Navigation("Posts");

                    b.Navigation("ReceivedRequests");

                    b.Navigation("SentRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
